---
- name: check uptime
  hosts: all
  tasks:
    - name: check uptime on target hosts
      command: uptime
      register: output
    - name: print the output
      debug:
       msg: "{{ output }}"
