---
- name: check uptime
  hosts: all
  tasks:
    - name: update the repo with centralized repo
      yum: 
       name: "*"
       state: latest
    - name: install apache2 package
      yum:
       name: "{{ package }}"
       state: present
    - name: change the file info
       copy: 
         src: /root/file.txt
         dest: /var/www/html/index.html
     - name: restart the service
       service:
        name: "{{ package }}"
        state: restart
        
        
        
        
